"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";
type Reservation={id:string;guests:number;baby?:number;notes:string|null;created_at:string;customers:{name:string;phone:string;allergies_requests:string|null}|null};
const iso=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
export default function ReservationsPage(){
 const [date,setDate]=useState(iso(new Date())); const [customDate,setCustomDate]=useState(false); const [service,setService]=useState("cena"); const [rows,setRows]=useState<Reservation[]>([]); const [loading,setLoading]=useState(true);
 const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);setDate(iso(d));setCustomDate(false)};
 useEffect(()=>{let live=true;(async()=>{setLoading(true);const {data}=await supabase.from("reservations").select("id,guests,notes,created_at,customers(name,phone,allergies_requests)").eq("reservation_date",date).eq("service",service).neq("status","cancellata").order("created_at");if(live){setRows((data||[]) as unknown as Reservation[]);setLoading(false)}})();return()=>{live=false}},[date,service]);
 const totals=useMemo(()=>({bookings:rows.length,guests:rows.reduce((a,r)=>a+(r.guests||0),0),baby:rows.reduce((a,r)=>a+(r.baby||0),0)}),[rows]);
 return <main><header><div><b>PRENOTAZIONI</b><span>Officina22</span></div><nav><a href="/">+ NUOVA</a><button className="account">ACCOUNT</button></nav></header><section className="card agenda"><div className="agendaTitle"><div><h1>Prenotazioni</h1><p>{new Date(date+"T12:00:00").toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"})}</p></div><a className="newBooking" href="/">+ NUOVA</a></div><label>DATA</label><div className="row"><button className={!customDate&&date===iso(new Date())?"selected":""} onClick={()=>{setDate(iso(new Date()));setCustomDate(false)}}>OGGI</button><button onClick={tomorrow}>DOMANI</button><label className="datePicker"><span>{customDate?new Date(date+"T12:00:00").toLocaleDateString("it-IT"):"SELEZIONA ALTRA DATA"}</span><input type="date" value={date} onChange={e=>{setDate(e.target.value);setCustomDate(true)}}/></label></div><label>SERVIZIO</label><div className="two"><button className={service==="pranzo"?"selected":""} onClick={()=>setService("pranzo")}>PRANZO</button><button className={service==="cena"?"selected":""} onClick={()=>setService("cena")}>CENA</button></div><div className="summary"><div><strong>{totals.bookings}</strong><span>PRENOTAZIONI</span></div><div><strong>{totals.guests}</strong><span>COPERTI</span></div><div><strong>{totals.baby}</strong><span>BABY</span></div></div><div className="bookingList">{loading?<p className="empty">Caricamento…</p>:rows.length===0?<div className="empty"><b>Nessuna prenotazione</b><span>per questo servizio</span></div>:rows.map(r=><article className="booking" key={r.id}><div className="bookingMain"><h2>{r.customers?.name||"Cliente"}</h2><div className="counts"><b>{r.guests}</b> coperti{(r.baby||0)>0&&<> · <b>{r.baby}</b> baby</>}</div></div><a className="phone" href={"tel:"+(r.customers?.phone||"")}>{r.customers?.phone||"—"}</a>{r.customers?.allergies_requests&&<div className="tags">{r.customers.allergies_requests}</div>}{r.notes&&<p className="bookingNotes">{r.notes}</p>}</article>)}</div></section></main>
}