"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type Channel={id:number;name:string};
const iso=(d:Date)=>d.toISOString().slice(0,10);
export default function Home(){
 const [date,setDate]=useState(iso(new Date())); const [service,setService]=useState("cena"); const [guests,setGuests]=useState(2);
 const [phone,setPhone]=useState(""); const [name,setName]=useState(""); const [channel,setChannel]=useState<number|undefined>(); const [channels,setChannels]=useState<Channel[]>([]);
 const [requests,setRequests]=useState(""); const [notes,setNotes]=useState(""); const [customerId,setCustomerId]=useState<string>(); const [history,setHistory]=useState(0); const [msg,setMsg]=useState("");
 useEffect(()=>{supabase.from("acquisition_channels").select("id,name").eq("active",true).order("sort_order").then(({data})=>{if(data){setChannels(data);setChannel(data[0]?.id)}})},[]);
 async function lookup(v:string){setPhone(v);setCustomerId(undefined);setHistory(0); if(v.replace(/\D/g,"").length<7)return; const {data}=await supabase.from("customers").select("*").eq("phone",v).maybeSingle(); if(data){setCustomerId(data.id);setName(data.name);setChannel(data.acquisition_channel_id);setRequests(data.allergies_requests||""); const h=await supabase.from("reservations").select("id",{count:"exact",head:true}).eq("customer_id",data.id);setHistory(h.count||0)}}
 async function save(){setMsg("");if(!phone||!name){setMsg("Inserisci telefono e nome cliente");return} let cid=customerId; if(!cid){const {data,error}=await supabase.from("customers").insert({name,phone,acquisition_channel_id:channel,allergies_requests:requests}).select("id").single();if(error){setMsg(error.message);return}cid=data.id}else await supabase.from("customers").update({name,acquisition_channel_id:channel,allergies_requests:requests}).eq("id",cid); const {error}=await supabase.from("reservations").insert({customer_id:cid,reservation_date:date,service,guests,notes}); if(error){setMsg("Accedi con un account per salvare la prenotazione.");return} setMsg("Prenotazione confermata");setPhone("");setName("");setRequests("");setNotes("");setCustomerId(undefined);setHistory(0)}
 const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);setDate(iso(d))};
 return <main><header><div><b>PRENOTAZIONI</b><span>Officina22</span></div><button className="account">ACCOUNT</button></header><section className="card"><h1>Nuova prenotazione</h1><label>DATA</label><div className="row"><button onClick={()=>setDate(iso(new Date()))}>OGGI</button><button onClick={tomorrow}>DOMANI</button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><label>SERVIZIO</label><div className="two"><button className={service==="pranzo"?"selected":""} onClick={()=>setService("pranzo")}>PRANZO</button><button className={service==="cena"?"selected":""} onClick={()=>setService("cena")}>CENA</button></div><label>PERSONE</label><div className="people">{[2,3,4,5,6,7].map(n=><button key={n} className={guests===n?"selected":""} onClick={()=>setGuests(n)}>{n}</button>)}<button onClick={()=>setGuests(guests+1)}>+</button></div><label>TELEFONO</label><input className="full" inputMode="tel" value={phone} onChange={e=>lookup(e.target.value)} placeholder="Numero di telefono"/><label>CLIENTE</label><input className="full" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome cliente"/>{customerId&&<div className="known">Cliente già presente · {history} prenotazioni precedenti</div>}<label>CANALE DI ACQUISIZIONE</label><div className="channels">{channels.map(c=><button key={c.id} className={channel===c.id?"selected":""} onClick={()=>setChannel(c.id)}>{c.name}</button>)}</div><label>INTOLLERANZE / RICHIESTE</label><input className="full" value={requests} onChange={e=>setRequests(e.target.value)} placeholder="Facoltativo"/><label>NOTE</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Facoltativo"/><button className="confirm" onClick={save}>CONFERMA PRENOTAZIONE</button>{msg&&<p className="msg">{msg}</p>}</section></main>}